--- #YAML:1.0
name:               Device-Blkid-E2fsprogs
version:            0.18
abstract:           Perl interface to e2fsprogs-based libblkid (v1.33 - v1.41.4)
author:
    - Raymond Mroz <mroz@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:       0
    Test::Builder:  0
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
