--- #YAML:1.0
name:               Device-Blkid-E2fsprogs
version:            0.38
abstract:           Perl interface to e2fsprogs-based libblkid (v1.33 - v1.41.4)
author:
    - Raymond Mroz <mroz@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:       0
    Test::Builder:  0
    Test::More:     0
resources:
    repository:  git://github.com/raymroz/Device--Blkid--E2fsprogs.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
