--- #YAML:1.0
name:                Device-Blkid-E2fsprogs
version:             0.14
abstract:            Perl interface to e2fsprogs-based libblkid (v1.33 - v1.41.4)
license:             ~
author:              
    - Raymond Mroz <mroz@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Exporter:                      0
    Test::Builder:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
